2025-05-10 18:29:46,668 [INFO] Pika version 1.3.2 connecting to ('::1', 5672, 0, 0)
2025-05-10 18:29:46,669 [ERROR] Socket failed to connect: <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 36320, 0, 0)>; error=111 (Connection refused)
2025-05-10 18:29:46,669 [ERROR] TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 5672, 0, 0))
2025-05-10 18:29:46,669 [ERROR] AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')
2025-05-10 18:29:46,669 [INFO] Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2025-05-10 18:29:46,670 [ERROR] Socket failed to connect: <socket.socket fd=10, family=2, type=1, proto=6, laddr=('127.0.0.1', 54224)>; error=111 (Connection refused)
2025-05-10 18:29:46,670 [ERROR] TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 5672))
2025-05-10 18:29:46,670 [ERROR] AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')
2025-05-10 18:29:46,670 [ERROR] AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused').
2025-05-10 18:29:46,670 [ERROR] AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')
2025-05-10 18:29:46,671 [ERROR] Connection workflow failed: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused'); first exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')
2025-05-10 18:29:46,671 [ERROR] Error in _create_connection().
Traceback (most recent call last):
  File "/home/milax/SD/sd_p1/dynamic-scaling/venv/lib/python3.11/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
2025-05-10 18:29:46,672 [INFO] InsultFilterService_0 registered at PYRO:obj_a951671621154d45ba31f7d4cee4094c@localhost:50152
2025-05-10 19:05:48,628 [INFO] Pika version 1.3.2 connecting to ('::1', 5672, 0, 0)
2025-05-10 19:05:48,629 [INFO] Socket connected: <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 50990, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 19:05:48,630 [INFO] Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f74ca5b8110>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f74ca5b8110> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2025-05-10 19:05:48,631 [ERROR] Socket EOF; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 50990, 0, 0)>
2025-05-10 19:05:48,631 [ERROR] Transport indicated EOF.
2025-05-10 19:05:48,631 [INFO] protocol.eof_received() elected to close: <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 50990, 0, 0)>
2025-05-10 19:05:48,631 [INFO] _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 50990, 0, 0)>
2025-05-10 19:05:48,631 [INFO] Deactivating transport: state=1; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 50990, 0, 0)>
2025-05-10 19:05:48,631 [ERROR] connection_lost: StreamLostError: ('Transport indicated EOF',)
2025-05-10 19:05:48,632 [INFO] AMQP stack terminated, failed to connect, or aborted: opened=False, error-arg=StreamLostError: ('Transport indicated EOF',); pending-error=None
2025-05-10 19:05:48,632 [ERROR] Probably incompatible Protocol Versions
2025-05-10 19:05:48,632 [INFO] Connection setup terminated due to IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",)
2025-05-10 19:05:48,632 [ERROR] AMQPConnector - reporting failure: AMQPConnectorAMQPHandshakeError: IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",)
2025-05-10 19:05:48,632 [INFO] Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2025-05-10 19:05:48,632 [INFO] Closing transport socket and unlinking: state=3; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 50990, 0, 0)>
2025-05-10 19:05:48,633 [INFO] InsultFilterService_0 registered at PYRO:obj_cec5ff9863274b9e9fbf96d1c45b1854@localhost:50152
2025-05-10 19:05:48,633 [INFO] Socket connected: <socket.socket fd=11, family=2, type=1, proto=6, laddr=('127.0.0.1', 34518), raddr=('127.0.0.1', 5672)>
2025-05-10 19:05:48,633 [INFO] Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f74ca5b9350>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f74ca5b9350> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2025-05-10 19:05:48,634 [ERROR] Socket EOF; <socket.socket fd=11, family=2, type=1, proto=6, laddr=('127.0.0.1', 34518)>
2025-05-10 19:05:48,634 [ERROR] Transport indicated EOF.
2025-05-10 19:05:48,634 [INFO] protocol.eof_received() elected to close: <socket.socket fd=11, family=2, type=1, proto=6, laddr=('127.0.0.1', 34518)>
2025-05-10 19:05:48,634 [INFO] _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=11, family=2, type=1, proto=6, laddr=('127.0.0.1', 34518)>
2025-05-10 19:05:48,634 [INFO] Deactivating transport: state=1; <socket.socket fd=11, family=2, type=1, proto=6, laddr=('127.0.0.1', 34518)>
2025-05-10 19:05:48,635 [ERROR] connection_lost: StreamLostError: ('Transport indicated EOF',)
2025-05-10 19:05:48,635 [INFO] AMQP stack terminated, failed to connect, or aborted: opened=False, error-arg=StreamLostError: ('Transport indicated EOF',); pending-error=None
2025-05-10 19:05:48,635 [ERROR] Probably incompatible Protocol Versions
2025-05-10 19:05:48,635 [INFO] Connection setup terminated due to IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",)
2025-05-10 19:05:48,635 [ERROR] AMQPConnector - reporting failure: AMQPConnectorAMQPHandshakeError: IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",)
2025-05-10 19:05:48,637 [ERROR] AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",); first exception - AMQPConnectorAMQPHandshakeError: IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",).
2025-05-10 19:05:48,637 [ERROR] AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",); first exception - AMQPConnectorAMQPHandshakeError: IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",)
2025-05-10 19:05:48,637 [INFO] Closing transport socket and unlinking: state=3; <socket.socket fd=11, family=2, type=1, proto=6, laddr=('127.0.0.1', 34518)>
2025-05-10 19:05:48,637 [ERROR] Connection workflow failed: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",); first exception - AMQPConnectorAMQPHandshakeError: IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",)
2025-05-10 19:05:48,638 [ERROR] Error in _create_connection().
Traceback (most recent call last):
  File "/home/milax/SD/sd_p1/dynamic-scaling/venv/lib/python3.11/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.IncompatibleProtocolError: StreamLostError: ('Transport indicated EOF',)
2025-05-10 19:06:41,444 [INFO] Pika version 1.3.2 connecting to ('::1', 5672, 0, 0)
2025-05-10 19:06:41,445 [INFO] Socket connected: <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 38034, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 19:14:02,107 [INFO] Pika version 1.3.2 connecting to ('::1', 5672, 0, 0)
2025-05-10 19:14:02,107 [INFO] Socket connected: <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 54716, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 19:14:02,108 [INFO] Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7430db8210>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7430db8210> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2025-05-10 19:14:02,109 [ERROR] Socket EOF; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 54716, 0, 0)>
2025-05-10 19:14:02,109 [ERROR] Transport indicated EOF.
2025-05-10 19:14:02,109 [INFO] protocol.eof_received() elected to close: <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 54716, 0, 0)>
2025-05-10 19:14:02,109 [INFO] _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 54716, 0, 0)>
2025-05-10 19:14:02,109 [INFO] Deactivating transport: state=1; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 54716, 0, 0)>
2025-05-10 19:14:02,110 [ERROR] connection_lost: StreamLostError: ('Transport indicated EOF',)
2025-05-10 19:14:02,110 [INFO] AMQP stack terminated, failed to connect, or aborted: opened=False, error-arg=StreamLostError: ('Transport indicated EOF',); pending-error=None
2025-05-10 19:14:02,110 [ERROR] Probably incompatible Protocol Versions
2025-05-10 19:14:02,110 [INFO] Connection setup terminated due to IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",)
2025-05-10 19:14:02,110 [ERROR] AMQPConnector - reporting failure: AMQPConnectorAMQPHandshakeError: IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",)
2025-05-10 19:14:02,110 [INFO] InsultFilterService_0 registered at PYRO:obj_d700e06a3f024f0d826afcab3a9a65d4@localhost:50152
2025-05-10 19:14:02,110 [INFO] Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2025-05-10 19:14:02,111 [INFO] Closing transport socket and unlinking: state=3; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 54716, 0, 0)>
2025-05-10 19:14:02,111 [INFO] Socket connected: <socket.socket fd=11, family=2, type=1, proto=6, laddr=('127.0.0.1', 38218), raddr=('127.0.0.1', 5672)>
2025-05-10 19:14:02,111 [INFO] Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7430db9490>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f7430db9490> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2025-05-10 19:14:02,112 [ERROR] Socket EOF; <socket.socket fd=11, family=2, type=1, proto=6, laddr=('127.0.0.1', 38218)>
2025-05-10 19:14:02,112 [ERROR] Transport indicated EOF.
2025-05-10 19:14:02,112 [INFO] protocol.eof_received() elected to close: <socket.socket fd=11, family=2, type=1, proto=6, laddr=('127.0.0.1', 38218)>
2025-05-10 19:14:02,112 [INFO] _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=11, family=2, type=1, proto=6, laddr=('127.0.0.1', 38218)>
2025-05-10 19:14:02,112 [INFO] Deactivating transport: state=1; <socket.socket fd=11, family=2, type=1, proto=6, laddr=('127.0.0.1', 38218)>
2025-05-10 19:14:02,112 [ERROR] connection_lost: StreamLostError: ('Transport indicated EOF',)
2025-05-10 19:14:02,112 [INFO] AMQP stack terminated, failed to connect, or aborted: opened=False, error-arg=StreamLostError: ('Transport indicated EOF',); pending-error=None
2025-05-10 19:14:02,112 [ERROR] Probably incompatible Protocol Versions
2025-05-10 19:14:02,112 [INFO] Connection setup terminated due to IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",)
2025-05-10 19:14:02,113 [ERROR] AMQPConnector - reporting failure: AMQPConnectorAMQPHandshakeError: IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",)
2025-05-10 19:14:02,113 [ERROR] AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",); first exception - AMQPConnectorAMQPHandshakeError: IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",).
2025-05-10 19:14:02,113 [ERROR] AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",); first exception - AMQPConnectorAMQPHandshakeError: IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",)
2025-05-10 19:14:02,113 [INFO] Closing transport socket and unlinking: state=3; <socket.socket fd=11, family=2, type=1, proto=6, laddr=('127.0.0.1', 38218)>
2025-05-10 19:14:02,113 [ERROR] Connection workflow failed: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",); first exception - AMQPConnectorAMQPHandshakeError: IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",)
2025-05-10 19:14:02,113 [ERROR] Error in _create_connection().
Traceback (most recent call last):
  File "/home/milax/SD/sd_p1/dynamic-scaling/venv/lib/python3.11/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.IncompatibleProtocolError: StreamLostError: ('Transport indicated EOF',)
2025-05-10 19:21:36,276 [INFO] Pika version 1.3.2 connecting to ('::1', 5672, 0, 0)
2025-05-10 19:21:36,278 [INFO] Socket connected: <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 35634, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 19:21:36,279 [INFO] Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fd30eb004d0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fd30eb004d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2025-05-10 19:21:36,284 [INFO] AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fd30eb004d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2025-05-10 19:21:36,284 [INFO] AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fd30eb004d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2025-05-10 19:21:36,284 [INFO] Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fd30eb004d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2025-05-10 19:21:36,284 [INFO] Created channel=1
2025-05-10 19:21:36,294 [INFO] InsultFilterService_0 registered at PYRO:obj_80cadf1f22864cc792b27d30afb21d4a@localhost:50152
2025-05-10 19:22:46,232 [INFO] Filtered text added: you're such a clown
2025-05-10 19:22:46,234 [INFO] Filtered text added: that was a moron move
2025-05-10 19:22:46,236 [INFO] Filtered text added: twit behavior again?
2025-05-10 19:22:46,238 [INFO] Filtered text added: what a loser you are
2025-05-10 19:40:00,836 [INFO] Pika version 1.3.2 connecting to ('::1', 5672, 0, 0)
2025-05-10 19:40:00,837 [INFO] Socket connected: <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 54996, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 19:40:00,838 [INFO] Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fbe72158310>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fbe72158310> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2025-05-10 19:40:00,838 [ERROR] Socket EOF; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 54996, 0, 0)>
2025-05-10 19:40:00,839 [ERROR] Transport indicated EOF.
2025-05-10 19:40:00,839 [INFO] protocol.eof_received() elected to close: <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 54996, 0, 0)>
2025-05-10 19:40:00,839 [INFO] _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 54996, 0, 0)>
2025-05-10 19:40:00,839 [INFO] Deactivating transport: state=1; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 54996, 0, 0)>
2025-05-10 19:40:00,839 [ERROR] connection_lost: StreamLostError: ('Transport indicated EOF',)
2025-05-10 19:40:00,839 [INFO] AMQP stack terminated, failed to connect, or aborted: opened=False, error-arg=StreamLostError: ('Transport indicated EOF',); pending-error=None
2025-05-10 19:40:00,839 [ERROR] Probably incompatible Protocol Versions
2025-05-10 19:40:00,839 [INFO] Connection setup terminated due to IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",)
2025-05-10 19:40:00,840 [ERROR] AMQPConnector - reporting failure: AMQPConnectorAMQPHandshakeError: IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",)
2025-05-10 19:40:00,840 [INFO] Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2025-05-10 19:40:00,840 [INFO] Closing transport socket and unlinking: state=3; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 54996, 0, 0)>
2025-05-10 19:40:00,841 [INFO] Socket connected: <socket.socket fd=11, family=2, type=1, proto=6, laddr=('127.0.0.1', 34318), raddr=('127.0.0.1', 5672)>
2025-05-10 19:40:00,841 [INFO] Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fbe72159590>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fbe72159590> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2025-05-10 19:40:00,842 [ERROR] Socket EOF; <socket.socket fd=11, family=2, type=1, proto=6, laddr=('127.0.0.1', 34318)>
2025-05-10 19:40:00,842 [ERROR] Transport indicated EOF.
2025-05-10 19:40:00,842 [INFO] protocol.eof_received() elected to close: <socket.socket fd=11, family=2, type=1, proto=6, laddr=('127.0.0.1', 34318)>
2025-05-10 19:40:00,842 [INFO] _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=11, family=2, type=1, proto=6, laddr=('127.0.0.1', 34318)>
2025-05-10 19:40:00,842 [INFO] Deactivating transport: state=1; <socket.socket fd=11, family=2, type=1, proto=6, laddr=('127.0.0.1', 34318)>
2025-05-10 19:40:00,842 [ERROR] connection_lost: StreamLostError: ('Transport indicated EOF',)
2025-05-10 19:40:00,842 [INFO] AMQP stack terminated, failed to connect, or aborted: opened=False, error-arg=StreamLostError: ('Transport indicated EOF',); pending-error=None
2025-05-10 19:40:00,843 [ERROR] Probably incompatible Protocol Versions
2025-05-10 19:40:00,843 [INFO] Connection setup terminated due to IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",)
2025-05-10 19:40:00,843 [ERROR] AMQPConnector - reporting failure: AMQPConnectorAMQPHandshakeError: IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",)
2025-05-10 19:40:00,843 [ERROR] AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",); first exception - AMQPConnectorAMQPHandshakeError: IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",).
2025-05-10 19:40:00,843 [ERROR] AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",); first exception - AMQPConnectorAMQPHandshakeError: IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",)
2025-05-10 19:40:00,843 [INFO] Closing transport socket and unlinking: state=3; <socket.socket fd=11, family=2, type=1, proto=6, laddr=('127.0.0.1', 34318)>
2025-05-10 19:40:00,843 [ERROR] Connection workflow failed: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",); first exception - AMQPConnectorAMQPHandshakeError: IncompatibleProtocolError: The protocol returned by the server is not supported: ("StreamLostError: ('Transport indicated EOF',)",)
2025-05-10 19:40:00,843 [ERROR] Error in _create_connection().
Traceback (most recent call last):
  File "/home/milax/SD/sd_p1/dynamic-scaling/venv/lib/python3.11/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.IncompatibleProtocolError: StreamLostError: ('Transport indicated EOF',)
2025-05-10 19:40:00,850 [INFO] InsultFilterService_0 registered at PYRO:obj_c0818233483a400d90ffbf565d65c33b@localhost:50152
2025-05-10 19:41:25,524 [INFO] InsultFilterService_0 registered at PYRO:obj_d0a77abb91084fffb25d3a0d9e59f565@localhost:50152
2025-05-10 19:41:25,524 [INFO] Pika version 1.3.2 connecting to ('::1', 5672, 0, 0)
2025-05-10 19:41:25,525 [INFO] Socket connected: <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 45146, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 19:41:25,526 [INFO] Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f2522100350>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f2522100350> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2025-05-10 19:41:25,533 [INFO] Aborting transport connection: state=1; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 45146, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 19:41:25,534 [INFO] _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 45146, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 19:41:25,534 [INFO] Deactivating transport: state=1; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 45146, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 19:41:25,534 [INFO] AMQP stack terminated, failed to connect, or aborted: opened=False, error-arg=None; pending-error=ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'
2025-05-10 19:41:25,534 [ERROR] Connection closed while authenticating indicating a probable authentication error
2025-05-10 19:41:25,534 [INFO] Connection setup terminated due to ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",)
2025-05-10 19:41:25,534 [ERROR] AMQPConnector - reporting failure: AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",)
2025-05-10 19:41:25,535 [INFO] Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2025-05-10 19:41:25,535 [INFO] Closing transport socket and unlinking: state=3; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 45146, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 19:41:25,538 [INFO] Socket connected: <socket.socket fd=11, family=2, type=1, proto=6, laddr=('127.0.0.1', 52846), raddr=('127.0.0.1', 5672)>
2025-05-10 19:41:25,539 [INFO] Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f2522101c90>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f2522101c90> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2025-05-10 19:41:25,541 [INFO] Aborting transport connection: state=1; <socket.socket fd=11, family=2, type=1, proto=6, laddr=('127.0.0.1', 52846), raddr=('127.0.0.1', 5672)>
2025-05-10 19:41:25,542 [INFO] _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=11, family=2, type=1, proto=6, laddr=('127.0.0.1', 52846), raddr=('127.0.0.1', 5672)>
2025-05-10 19:41:25,542 [INFO] Deactivating transport: state=1; <socket.socket fd=11, family=2, type=1, proto=6, laddr=('127.0.0.1', 52846), raddr=('127.0.0.1', 5672)>
2025-05-10 19:41:25,542 [INFO] AMQP stack terminated, failed to connect, or aborted: opened=False, error-arg=None; pending-error=ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'
2025-05-10 19:41:25,542 [ERROR] Connection closed while authenticating indicating a probable authentication error
2025-05-10 19:41:25,542 [INFO] Connection setup terminated due to ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",)
2025-05-10 19:41:25,542 [ERROR] AMQPConnector - reporting failure: AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",)
2025-05-10 19:41:25,543 [ERROR] AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",); first exception - AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",).
2025-05-10 19:41:25,543 [ERROR] AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",); first exception - AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",)
2025-05-10 19:41:25,544 [INFO] Closing transport socket and unlinking: state=3; <socket.socket fd=11, family=2, type=1, proto=6, laddr=('127.0.0.1', 52846), raddr=('127.0.0.1', 5672)>
2025-05-10 19:41:25,545 [ERROR] Connection workflow failed: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",); first exception - AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",)
2025-05-10 19:41:25,545 [ERROR] Error in _create_connection().
Traceback (most recent call last):
  File "/home/milax/SD/sd_p1/dynamic-scaling/venv/lib/python3.11/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.ProbableAuthenticationError: ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'
2025-05-10 21:04:18,068 [INFO] Pika version 1.3.2 connecting to ('::1', 5672, 0, 0)
2025-05-10 21:04:18,069 [INFO] Socket connected: <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 39690, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:04:18,071 [INFO] Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8530894150>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8530894150> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2025-05-10 21:04:18,077 [INFO] AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8530894150> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2025-05-10 21:04:18,077 [INFO] AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8530894150> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2025-05-10 21:04:18,078 [INFO] Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f8530894150> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2025-05-10 21:04:18,078 [INFO] Created channel=1
2025-05-10 21:04:18,710 [INFO] Aborting transport connection: state=1; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 39690, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:04:18,710 [INFO] _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 39690, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:04:18,710 [INFO] Deactivating transport: state=1; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 39690, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:04:18,711 [INFO] AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByBroker: (320) "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
2025-05-10 21:04:18,711 [INFO] Stack terminated due to ConnectionClosedByBroker: (320) "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
2025-05-10 21:04:18,712 [INFO] Closing transport socket and unlinking: state=3; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 39690, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:04:18,712 [ERROR] Unexpected connection close detected: ConnectionClosedByBroker: (320) "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
2025-05-10 21:06:27,653 [INFO] Pika version 1.3.2 connecting to ('::1', 5672, 0, 0)
2025-05-10 21:06:27,654 [INFO] Socket connected: <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 57456, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:06:27,656 [INFO] Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f2030eb00d0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f2030eb00d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2025-05-10 21:06:27,663 [INFO] AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f2030eb00d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2025-05-10 21:06:27,663 [INFO] AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f2030eb00d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2025-05-10 21:06:27,664 [INFO] Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f2030eb00d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2025-05-10 21:06:27,665 [INFO] Created channel=1
2025-05-10 21:06:28,274 [INFO] Aborting transport connection: state=1; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 57456, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:06:28,275 [INFO] _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 57456, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:06:28,275 [INFO] Deactivating transport: state=1; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 57456, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:06:28,276 [INFO] AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByBroker: (320) "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
2025-05-10 21:06:28,285 [INFO] Stack terminated due to ConnectionClosedByBroker: (320) "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
2025-05-10 21:06:28,285 [INFO] Closing transport socket and unlinking: state=3; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 57456, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:06:28,286 [ERROR] Unexpected connection close detected: ConnectionClosedByBroker: (320) "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
2025-05-10 21:07:33,987 [INFO] Pika version 1.3.2 connecting to ('::1', 5672, 0, 0)
2025-05-10 21:07:33,988 [INFO] Socket connected: <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 43250, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:07:33,989 [INFO] Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fd6841e83d0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fd6841e83d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2025-05-10 21:07:33,993 [INFO] Aborting transport connection: state=1; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 43250, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:07:33,993 [INFO] _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 43250, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:07:33,993 [INFO] Deactivating transport: state=1; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 43250, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:07:33,993 [INFO] AMQP stack terminated, failed to connect, or aborted: opened=False, error-arg=None; pending-error=ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'
2025-05-10 21:07:33,993 [ERROR] Connection closed while authenticating indicating a probable authentication error
2025-05-10 21:07:33,993 [INFO] InsultFilterService_0 registered at PYRO:obj_fb4c8de4d5c24f37a4ee828058f86609@localhost:50152
2025-05-10 21:07:33,993 [INFO] Connection setup terminated due to ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",)
2025-05-10 21:07:33,994 [ERROR] AMQPConnector - reporting failure: AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",)
2025-05-10 21:07:33,994 [INFO] Pika version 1.3.2 connecting to ('127.0.0.1', 5672)
2025-05-10 21:07:33,994 [INFO] Closing transport socket and unlinking: state=3; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 43250, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:07:33,994 [INFO] Socket connected: <socket.socket fd=11, family=2, type=1, proto=6, laddr=('127.0.0.1', 60818), raddr=('127.0.0.1', 5672)>
2025-05-10 21:07:33,995 [INFO] Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fd6841e9d50>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fd6841e9d50> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2025-05-10 21:07:34,000 [INFO] Aborting transport connection: state=1; <socket.socket fd=11, family=2, type=1, proto=6, laddr=('127.0.0.1', 60818), raddr=('127.0.0.1', 5672)>
2025-05-10 21:07:34,000 [INFO] _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=11, family=2, type=1, proto=6, laddr=('127.0.0.1', 60818), raddr=('127.0.0.1', 5672)>
2025-05-10 21:07:34,001 [INFO] Deactivating transport: state=1; <socket.socket fd=11, family=2, type=1, proto=6, laddr=('127.0.0.1', 60818), raddr=('127.0.0.1', 5672)>
2025-05-10 21:07:34,001 [INFO] AMQP stack terminated, failed to connect, or aborted: opened=False, error-arg=None; pending-error=ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'
2025-05-10 21:07:34,001 [ERROR] Connection closed while authenticating indicating a probable authentication error
2025-05-10 21:07:34,001 [INFO] Connection setup terminated due to ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",)
2025-05-10 21:07:34,001 [ERROR] AMQPConnector - reporting failure: AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",)
2025-05-10 21:07:34,001 [ERROR] AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",); first exception - AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",).
2025-05-10 21:07:34,002 [ERROR] AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",); first exception - AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",)
2025-05-10 21:07:34,002 [INFO] Closing transport socket and unlinking: state=3; <socket.socket fd=11, family=2, type=1, proto=6, laddr=('127.0.0.1', 60818), raddr=('127.0.0.1', 5672)>
2025-05-10 21:07:34,002 [ERROR] Connection workflow failed: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",); first exception - AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",)
2025-05-10 21:07:34,003 [ERROR] Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.ProbableAuthenticationError: ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'
2025-05-10 21:11:38,284 [INFO] Pika version 1.3.2 connecting to ('::1', 5672, 0, 0)
2025-05-10 21:11:38,285 [INFO] Socket connected: <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 55278, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:11:38,287 [INFO] Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fa3fb03c150>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fa3fb03c150> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2025-05-10 21:11:38,293 [INFO] AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fa3fb03c150> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2025-05-10 21:11:38,293 [INFO] AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fa3fb03c150> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2025-05-10 21:11:38,294 [INFO] InsultFilterService_0 registered at PYRO:obj_7a1f74aaaa91461e8bc30fb58ede7b07@localhost:50152
2025-05-10 21:11:38,294 [INFO] Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fa3fb03c150> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2025-05-10 21:11:38,296 [INFO] Created channel=1
2025-05-10 21:14:31,009 [INFO] Aborting transport connection: state=1; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 55278, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:14:31,009 [INFO] _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 55278, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:14:31,010 [INFO] Deactivating transport: state=1; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 55278, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:14:31,010 [INFO] AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByBroker: (320) "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
2025-05-10 21:14:31,011 [INFO] Stack terminated due to ConnectionClosedByBroker: (320) "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
2025-05-10 21:14:31,012 [INFO] Closing transport socket and unlinking: state=3; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 55278, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:14:31,014 [ERROR] Unexpected connection close detected: ConnectionClosedByBroker: (320) "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
2025-05-10 21:15:50,314 [INFO] Pika version 1.3.2 connecting to ('::1', 5672, 0, 0)
2025-05-10 21:15:50,316 [INFO] Socket connected: <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 50664, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:15:50,318 [INFO] Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f2d4f0504d0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f2d4f0504d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2025-05-10 21:15:50,323 [INFO] InsultFilterService_0 registered at PYRO:obj_fcca5d8c7e754f8b8424415d490ea627@localhost:50152
2025-05-10 21:15:50,331 [INFO] AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f2d4f0504d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2025-05-10 21:15:50,332 [INFO] AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f2d4f0504d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2025-05-10 21:15:50,332 [INFO] Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f2d4f0504d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2025-05-10 21:15:50,332 [INFO] Created channel=1
2025-05-10 21:15:51,005 [INFO] Aborting transport connection: state=1; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 50664, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:15:51,006 [INFO] _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 50664, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:15:51,006 [INFO] Deactivating transport: state=1; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 50664, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:15:51,007 [INFO] AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByBroker: (320) "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
2025-05-10 21:15:51,008 [INFO] Stack terminated due to ConnectionClosedByBroker: (320) "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
2025-05-10 21:15:51,008 [INFO] Closing transport socket and unlinking: state=3; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 50664, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:15:51,009 [ERROR] Unexpected connection close detected: ConnectionClosedByBroker: (320) "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
2025-05-10 21:19:52,180 [INFO] Pika version 1.3.2 connecting to ('::1', 5672, 0, 0)
2025-05-10 21:19:52,181 [INFO] Socket connected: <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 35318, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:19:52,183 [INFO] Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fa8218943d0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fa8218943d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2025-05-10 21:19:52,188 [INFO] InsultFilterService_0 registered at PYRO:obj_cd1f234e893c41df921f0cafc9f9e678@localhost:50152
2025-05-10 21:19:52,188 [INFO] AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fa8218943d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2025-05-10 21:19:52,188 [INFO] AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fa8218943d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2025-05-10 21:19:52,189 [INFO] Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fa8218943d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2025-05-10 21:19:52,189 [INFO] Created channel=1
2025-05-10 21:19:54,881 [INFO] Aborting transport connection: state=1; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 35318, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:19:54,881 [INFO] _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 35318, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:19:54,881 [INFO] Deactivating transport: state=1; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 35318, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:19:54,882 [INFO] AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByBroker: (320) "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
2025-05-10 21:19:54,883 [INFO] Stack terminated due to ConnectionClosedByBroker: (320) "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
2025-05-10 21:19:54,883 [INFO] Closing transport socket and unlinking: state=3; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 35318, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:19:54,884 [ERROR] Unexpected connection close detected: ConnectionClosedByBroker: (320) "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
2025-05-10 21:21:18,011 [INFO] Pika version 1.3.2 connecting to ('::1', 5672, 0, 0)
2025-05-10 21:21:18,012 [INFO] Socket connected: <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 35032, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:21:18,014 [INFO] Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f05184942d0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f05184942d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2025-05-10 21:21:18,018 [INFO] InsultFilterService_0 registered at PYRO:obj_6e97dcfcf8ef454fa411c194b632eaae@localhost:50152
2025-05-10 21:21:18,018 [INFO] AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f05184942d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2025-05-10 21:21:18,019 [INFO] AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f05184942d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2025-05-10 21:21:18,019 [INFO] Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f05184942d0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2025-05-10 21:21:18,020 [INFO] Created channel=1
2025-05-10 21:21:20,429 [INFO] Aborting transport connection: state=1; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 35032, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:21:20,429 [INFO] _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 35032, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:21:20,429 [INFO] Deactivating transport: state=1; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 35032, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:21:20,429 [INFO] AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByBroker: (320) "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
2025-05-10 21:21:20,429 [INFO] Stack terminated due to ConnectionClosedByBroker: (320) "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
2025-05-10 21:21:20,430 [INFO] Closing transport socket and unlinking: state=3; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 35032, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:21:20,430 [ERROR] Unexpected connection close detected: ConnectionClosedByBroker: (320) "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
2025-05-10 21:27:19,945 [INFO] Pika version 1.3.2 connecting to ('::1', 5672, 0, 0)
2025-05-10 21:27:19,946 [INFO] Socket connected: <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 56550, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:27:19,947 [INFO] Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fda2e63bfd0>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fda2e63bfd0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2025-05-10 21:27:19,948 [INFO] InsultFilterService_0 registered at PYRO:obj_2f7d4220f9e74306bab6824ca2f63080@localhost:50152
2025-05-10 21:27:19,951 [INFO] AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fda2e63bfd0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2025-05-10 21:27:19,951 [INFO] AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fda2e63bfd0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2025-05-10 21:27:19,952 [INFO] Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7fda2e63bfd0> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2025-05-10 21:27:19,954 [INFO] Created channel=1
2025-05-10 21:27:27,169 [INFO] Aborting transport connection: state=1; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 56550, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:27:27,170 [INFO] _AsyncTransportBase._initate_abort(): Initiating abrupt asynchronous transport shutdown: state=1; error=None; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 56550, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:27:27,170 [INFO] Deactivating transport: state=1; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 56550, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:27:27,170 [INFO] AMQP stack terminated, failed to connect, or aborted: opened=True, error-arg=None; pending-error=ConnectionClosedByBroker: (320) "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
2025-05-10 21:27:27,170 [INFO] Stack terminated due to ConnectionClosedByBroker: (320) "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
2025-05-10 21:27:27,170 [INFO] Closing transport socket and unlinking: state=3; <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 56550, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:27:27,170 [ERROR] Unexpected connection close detected: ConnectionClosedByBroker: (320) "CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'"
2025-05-10 21:32:43,355 [INFO] Pika version 1.3.2 connecting to ('::1', 5672, 0, 0)
2025-05-10 21:32:43,356 [INFO] Socket connected: <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 55658, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:32:43,358 [INFO] Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f3e829fc510>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f3e829fc510> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2025-05-10 21:32:43,365 [INFO] InsultFilterService_0 registered at PYRO:obj_113c0f45de9141d4ae36fa590885e23c@localhost:50152
2025-05-10 21:32:43,366 [INFO] AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f3e829fc510> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2025-05-10 21:32:43,366 [INFO] AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f3e829fc510> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2025-05-10 21:32:43,366 [INFO] Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f3e829fc510> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2025-05-10 21:32:43,367 [INFO] Created channel=1
2025-05-10 21:44:05,010 [INFO] Pika version 1.3.2 connecting to ('::1', 5672, 0, 0)
2025-05-10 21:44:05,011 [INFO] Socket connected: <socket.socket fd=10, family=10, type=1, proto=6, laddr=('::1', 40246, 0, 0), raddr=('::1', 5672, 0, 0)>
2025-05-10 21:44:05,012 [INFO] Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f62d3724090>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f62d3724090> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>).
2025-05-10 21:44:05,019 [INFO] AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f62d3724090> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2025-05-10 21:44:05,020 [INFO] AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f62d3724090> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2025-05-10 21:44:05,020 [INFO] Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f62d3724090> params=<ConnectionParameters host=localhost port=5672 virtual_host=/ ssl=False>>
2025-05-10 21:44:05,021 [INFO] Created channel=1
2025-05-10 21:44:05,037 [INFO] InsultFilterService_0 registered at PYRO:obj_22b93e3e5eb54d848fb81bb848d56acc@localhost:50152
